# created by eselect-repo

[FireBurn]
location = /var/db/repos/FireBurn
sync-type = git
sync-uri = https://github.com/FireBurn/Overlay.git




[gamerlay]
location = /var/db/repos/gamerlay
sync-type = git
sync-uri = https://anongit.gentoo.org/git/proj/gamerlay.git

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[kde]
location = /var/db/repos/kde
sync-type = git
sync-uri = https://anongit.gentoo.org/git/proj/kde.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git
