CC=clang
CXX=clang++
CFLAGS="-O3 -pipe -march=native -U__GNUC__ -D__GNUC__=14"
CXXFLAGS="${CFLAGS}"
LDFLAGS="${CFLAGS}" # -Wl,-O1 -Wl,--as-needed -Wl,--undefined-version"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
