CC=clang
CXX=clang++
CFLAGS="-O2 -pipe -flto=thin"
CXXFLAGS="${CFLAGS}"
LD="ld.bfd"
LDFLAGS="${CFLAGS} -Wl,-O1 -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--undefined-version"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
STRIP="llvm-strip"
